// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: demo/v1/demo.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DemoServiceCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DemoServiceCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DemoServiceCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DemoServiceCreateRequestMultiError, or nil if none found.
func (m *DemoServiceCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DemoServiceCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DemoServiceCreateRequestMultiError(errors)
	}

	return nil
}

// DemoServiceCreateRequestMultiError is an error wrapping multiple validation
// errors returned by DemoServiceCreateRequest.ValidateAll() if the designated
// constraints aren't met.
type DemoServiceCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DemoServiceCreateRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DemoServiceCreateRequestMultiError) AllErrors() []error { return m }

// DemoServiceCreateRequestValidationError is the validation error returned by
// DemoServiceCreateRequest.Validate if the designated constraints aren't met.
type DemoServiceCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DemoServiceCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DemoServiceCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DemoServiceCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DemoServiceCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DemoServiceCreateRequestValidationError) ErrorName() string {
	return "DemoServiceCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DemoServiceCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDemoServiceCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DemoServiceCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DemoServiceCreateRequestValidationError{}

// Validate checks the field values on DemoServiceCreateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DemoServiceCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DemoServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DemoServiceCreateResponseMultiError, or nil if none found.
func (m *DemoServiceCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DemoServiceCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DemoServiceCreateResponseMultiError(errors)
	}

	return nil
}

// DemoServiceCreateResponseMultiError is an error wrapping multiple validation
// errors returned by DemoServiceCreateResponse.ValidateAll() if the
// designated constraints aren't met.
type DemoServiceCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DemoServiceCreateResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DemoServiceCreateResponseMultiError) AllErrors() []error { return m }

// DemoServiceCreateResponseValidationError is the validation error returned by
// DemoServiceCreateResponse.Validate if the designated constraints aren't met.
type DemoServiceCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DemoServiceCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DemoServiceCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DemoServiceCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DemoServiceCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DemoServiceCreateResponseValidationError) ErrorName() string {
	return "DemoServiceCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DemoServiceCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDemoServiceCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DemoServiceCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DemoServiceCreateResponseValidationError{}
