# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo/v1/demo.proto

require 'google/protobuf'

require 'google/api/annotations_pb'
require 'validate/validate_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("demo/v1/demo.proto", :syntax => :proto3) do
    add_message "demo.api.v1.DemoServiceCreateRequest" do
      optional :id, :int64, 1, json_name: "id"
    end
    add_message "demo.api.v1.DemoServiceCreateResponse" do
    end
  end
end

module Demo
  module Api
    module V1
      DemoServiceCreateRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.api.v1.DemoServiceCreateRequest").msgclass
      DemoServiceCreateResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("demo.api.v1.DemoServiceCreateResponse").msgclass
    end
  end
end
