# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: demo/v1/demo.proto for package 'demo.api.v1'

require 'grpc'
require 'demo/v1/demo_pb'

module Demo
  module Api
    module V1
      module DemoService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'demo.api.v1.DemoService'

          rpc :Create, ::Demo::Api::V1::DemoServiceCreateRequest, ::Demo::Api::V1::DemoServiceCreateResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
